services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: dotfiles
    stdin_open: true
    tty: true
    volumes:
      - .:/app
      - dotfiles-logs:/root/.local/state/vitualizz-dotfiles

  test:
    build:
      context: .
      dockerfile: Dockerfile.test
    container_name: dotfiles-test
    volumes:
      - .:/app
    working_dir: /app
    command: ["go", "test", "./...", "-v"]

  shell:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: dotfiles-shell
    stdin_open: true
    tty: true
    entrypoint: ["/bin/bash"]

volumes:
  dotfiles-logs: